library(tidyverse)
setwd('/Volumes/Image_Data/M28iCreiGFP_Ddit3cKO_Nrp2IFs/Analysis_Glomeruli/')

#'Process Glomeruli ROIs for Extraction- Updated for M28/Ddit3
#'@description Merge ROI file with glomeruluar locations & slice annotations tsv to set up extraction of glomerular subregions from full-res OB Datasets
#'@param roi_path (str) full path to roi file
#'    Slice: 1-indexed. Z plane of interest in final image set. Should be in saved ROI set
#'    X: um location of glomerulus (code assumes um -> px mapping is correct on downsampled and full res-images). Should be in saved ROI set
#'    Y: um location of glomerulus. Should be in saved ROI set
#'@param tsv_path (str) full path to slice annotation file. ASSUMES .nd2 FULL RES FILE IS IN SAME DIRECTORY
#'    slice_order: 0-indexed. Slice of the original .nd2 file. Generated by Process_OB_Scans
#'    image_file: relative path to original .nd2 file of interest. Generated by Process_OB_Scans
#'    flip_bool: boolean, should image be flipped. Generated by Process_OB_Scans
#'    output_file: file name for the output file (animal name). Generated by Process OB_Scans
#'@param animal_name (str) giving animal name to filter slice annotation file for (must be found in output_file column of tsv_path)
#'@param glom_nums (numeric vec of length 4) number of images for each glomerulus in roi_path, in order LLateral_GFP, RLateral_GFP, LMedial_GFP, RMedial_GFP.
#'@return (df) With mapping of interest 
process_rois_for_extraction_m28_ddit3 <- function(roi_path, tsv_path, animal_name, glom_nums) {
  #Assume .nd2 files will be found in same directory as the tsv.
  nd2_base <- str_split(tsv_path, '/')[[1]] %>% .[1:length(.)-1] %>% paste0(collapse = '/')
  
  #Load and Annotate ROI File 
  glom_order <- c('LLateral','RLateral','LMedial','RMedial')
  roi_file <- read_csv(roi_path) %>%
    mutate('Glomerulus' = rep(glom_order,
                              times = glom_nums))
  
  #Merge ROIs with Slice Annotations
  read_tsv(tsv_path) %>%
    mutate('Slice'= as.numeric(as.character(out_order)) + 1) %>% #0 index in Tsv -> 1 index from ROIs
    filter(output_file == animal_name) %>%
    right_join(roi_file,
               by = 'Slice') %>%
    mutate('image_file' = paste0(nd2_base, '/', image_file)) %>%
    dplyr::select(output_file, image_file, Glomerulus, slice_order, Slice, X, Y, flip_bool)
}

p28_exp1_annotations <- process_rois_for_extraction_m28_ddit3(roi_path = '/Volumes/Image_Data/M28iCreiGFP_Ddit3cKO_Nrp2IFs/5-19-22_4wkOBSect_Exp1/7-30-21_4250_4wkMor28_Exp1_Glomeruli.csv',
                                                              tsv_path = '/Volumes/Image_Data/M28iCreiGFP_Ddit3cKO_Nrp2IFs/5-19-22_4wkOBSect_Exp1/Slice_Lookup_Table.tsv',
                                                              animal_name = '7-30-21_4250_4wkMor28_Exp1',
                                                              glom_nums = c(9,11,5,6))

#write_csv(p28_exp1_annotations,'/Volumes/Image_Data/M28iCreiGFP_Ddit3cKO_Nrp2IFs/Analysis_Glomeruli/Rois_To_Extract/7-30-21_4250_4wkMor28_Exp1.csv')
